import assert from 'node:assert/strict';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { reportWorkbookBytes } from '../../test/fixtures/eyecheckReportWorkbook.js';
import { openEyecheckWorkbook } from '../../src/utils/eyecheckWorkbook.js';
import { unzipSync, zipSync, strFromU8, strToU8 } from 'fflate';

const root = fileURLToPath(new URL('./', import.meta.url));
await mkdir(`${root}screenshots`, { recursive: true });
await mkdir(`${root}samples`, { recursive: true });
const tab = (...fields) => fields.join('\t');
const date = '2026-09-09 09:00:00';
const log = (text) => `[${date}: ${text} 확인 UserName : 홍예시 UserID : DEMO]`;
const mail = [tab('DEMO-WEB-01', 'CPU Utilization MAJOR occurred(91 %)' + log('김예시 책임 문자'), date, '192.0.2.10'), tab('DEMO-DB-01', '/data (Filesystem)\nUtilization\tMAJOR occurred(92 %)' + log('이예시 선임 문자'), date, '192.0.2.11')].join('\n');
const gems = [tab('DEMO-WEB-01', 'CPU Utilization MAJOR occurred(91 %)' + log('김예시 책임 문자')), tab('DEMO-DB-01', '/data Utilization MAJOR occurred(92 %)' + log('이예시 선임 문자'))].join('\n');
const redirect = [tab('DEMO-WEB-01', 'CPU Utilization MAJOR occurred(91 %)' + log('김예시 책임 문자'), date, '192.0.2.10'), tab('DEMO-DB-01', '/data\nUtilization\tMAJOR occurred(92 %)' + log('이예시 선임 문자'), date, '192.0.2.11'), tab('DEMO-HOLD-01', 'Agent Status DOWN occurred("false")' + log('s 점검 중 skip'), date, '192.0.2.12')].join('\n');
const backupRow = (status, policy) => tab(status, 'Backup', 'Done', 'DEMO-CLIENT', 'Full', policy, '2026-09-09 오전 9:00:00', '00:03:00', 'DEMO');
const backup = [backupRow('0', 'DEMO_SUCCESS'), backupRow('1', 'DEMO_PARTIAL'), backupRow('58', 'DEMO_DB_DAILY'), backupRow('84', 'DEMO_WEB_DAILY')].join('\n');
const persistent = ['김예시 책임 문자', '김예시 책임 / 이예시 선임 문자', '담당자 확인중'].map((text, i) => tab('2일 1시간', 'DEMO>운영', `DEMO-SRV-0${i + 1}`, '/data Utilization MAJOR occurred(91 %)' + log(text), date, `192.0.2.${20 + i}`)).join('\n');
const icheck = [tab('2026-09-09', 'DEMO', 'DEMO-WEB-01', 'SA3A-1', 'DEMO', 'Server', 'MODEL-A', '-', '주황 점등', '1조', '홍예시', '김예시 책임', '확인 요청'), tab('2026-09-09', 'DEMO', 'DEMO-DB-01', 'SA3A-2', 'DEMO', 'Server', 'MODEL-B', '-', '빨강 점등', '1조', '홍예시', '이예시 선임', '확인 요청')].join('\n');
const samples = { mail, gems, redirect, backup, persistent, icheck };
for (const [name, value] of Object.entries(samples)) await writeFile(`${root}samples/${name}.txt`, value);
const practiceParts = unzipSync(reportWorkbookBytes());
practiceParts['[Content_Types].xml'] = strToU8(strFromU8(practiceParts['[Content_Types].xml']).replace('</Types>', [1, 2, 3].map(n => `<Override PartName="/xl/worksheets/sheet${n}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join('') + '</Types>'));
await writeFile(`${root}samples/eyecheck-practice.xlsx`, zipSync(practiceParts));
const { chromium } = await import(process.env.GUIDE_PLAYWRIGHT_MODULE || '/tmp/eyecheck-ui-tools/node_modules/playwright/index.mjs');
const browser = await chromium.launch({ headless: true });
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, permissions: ['clipboard-read', 'clipboard-write'] });
const font = await readFile(process.env.GUIDE_FONT || '/tmp/eyecheck-browser-libs/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc');
await context.route('**/__guide-font', route => route.fulfill({ contentType: 'font/ttf', body: font }));
await context.addInitScript(() => document.addEventListener('DOMContentLoaded', () => {
  const style = document.createElement('style');
  style.textContent = '@font-face{font-family:GuideKorean;src:url(/__guide-font)}body,input,button,select,textarea,pre{font-family:GuideKorean,sans-serif!important}';
  document.head.append(style);
}));
const page = await context.newPage();
const errors = [];
page.on('pageerror', err => errors.push(err.message));
const results = {};
const goto = async path => { await page.goto(`${process.env.GUIDE_BASE_URL || 'http://127.0.0.1:5173'}${path}`); await page.evaluate(() => document.fonts.ready); };
const shot = async (name, locator) => {
  await page.evaluate(() => document.fonts.ready);
  if (locator) await locator.screenshot({ path: `${root}screenshots/${name}.png`, animations: 'disabled' });
  else await page.screenshot({ path: `${root}screenshots/${name}.png`, fullPage: true, animations: 'disabled' });
  if (!locator) {
    const panels = page.locator('section.panel');
    for (let i = 0; i < await panels.count(); i++) {
      if (!await panels.nth(i).isVisible()) continue;
      await panels.nth(i).screenshot({ path: `${root}screenshots/${name}-panel-${i}.png`, animations: 'disabled' });
    }
  }
  console.log(`Captured ${name}`);
};
const clipboard = async () => page.evaluate(() => navigator.clipboard.readText());
try {
  await goto('/foreign-mail');
  const links = await page.locator('nav a').evaluateAll(nodes => nodes.map(n => n.getAttribute('href')));
  assert.ok(links.indexOf('/persistent-redirect') < links.indexOf('/auto-backup-error-filter'));
  await page.locator('textarea').fill(mail);
  await page.getByRole('button', { name: '메일 전체 복사', exact: true }).click();
  results.mail = await clipboard();
  assert.match(results.mail, /DEMO-DB-01/);
  assert.doesNotMatch(results.mail, /UserName|김예시/);
  assert.match(results.mail, /Filesystem\) Utilization MAJOR/);
  await shot('01-mail');
  await page.getByRole('button', { name: '열 순서 설정', exact: true }).click();
  await shot('02-mail-order');
  await goto('/gems-message');
  await page.locator('textarea').fill(gems);
  await shot('03-gems-clean');
  await page.locator('input[value=report]').check();
  await page.getByPlaceholder('정지운', { exact: true }).fill('홍예시');
  results.gems = await page.locator('pre').innerText();
  assert.match(results.gems, /홍예시/);
  assert.doesNotMatch(results.gems, /UserName/);
  await shot('04-gems-report');
  await goto('/persistent-redirect');
  await page.getByPlaceholder('정지운', { exact: true }).fill('홍예시');
  await page.getByLabel('원본 데이터', { exact: true }).fill(redirect);
  for (const host of ['DEMO-WEB-01', 'DEMO-DB-01']) {
    await page.locator('div.p-4.rounded-lg.border').filter({ hasText: host }).getByRole('button', { name: '전달 추가', exact: true }).click();
  }
  assert.equal(await page.getByRole('button', { name: '추가 취소', exact: true }).count(), 2);
  await shot('05-redirect');
  await page.getByRole('button', { name: '전체 복사', exact: true }).click();
  results.redirect = await clipboard();
  assert.match(results.redirect, /DEMO-WEB-01/);
  assert.match(results.redirect, /DEMO-DB-01/);
  await shot('06-redirect-output', page.locator('#persistent-redirect-output'));
  await page.getByRole('button', { name: '해외메일', exact: true }).click();
  await shot('07-redirect-mail', page.locator('#persistent-redirect-output'));
  await goto('/auto-backup-error-filter');
  await page.locator('textarea').fill(backup);
  await page.getByRole('button', { name: 'Outlook 행 복사', exact: true }).first().click();
  await page.getByRole('button', { name: '표 복사됨', exact: true }).first().waitFor();
  results.backup = await clipboard();
  assert.match(results.backup, /DEMO_DB_DAILY/);
  assert.doesNotMatch(results.backup, /DEMO_SUCCESS|DEMO_PARTIAL/);
  await shot('08-backup');
  await goto('/persistent-event-excel');
  await page.locator('textarea').fill(persistent);
  assert.equal(await page.getByRole('button', { name: '엑셀 파일 추출', exact: true }).isDisabled(), true);
  await shot('09-excel-review');
  await page.getByRole('checkbox', { name: '김예시 책임', exact: true }).check();
  await page.getByRole('checkbox', { name: '이예시 선임', exact: true }).check();
  await page.getByRole('button', { name: '선택 완료', exact: true }).click();
  await page.getByLabel('3행 담당자 직접 입력', { exact: true }).fill('박예시 책임');
  await page.getByLabel('3행 담당자 직접 입력', { exact: true }).press('Enter');
  const excelWait = page.waitForEvent('download');
  await page.getByRole('button', { name: '엑셀 파일 추출', exact: true }).click();
  const excel = await excelWait;
  await excel.saveAs(`${root}samples/persistent-result.xlsx`);
  const xml = Object.values(unzipSync(new Uint8Array(await readFile(await excel.path())))).map(bytes => strFromU8(bytes)).join('\n');
  assert.match(xml, /박예시 책임/);
  assert.match(xml, /이예시 선임/);
  results.persistent = '담당자 확정 및 XLSX 다운로드 검증 완료';
  await shot('10-excel-result');
  await goto('/eyecheck-light-log');
  await page.locator('input[type=file]').setInputFiles(`${root}samples/eyecheck-practice.xlsx`);
  await page.getByText('eyecheck-practice.xlsx', { exact: true }).waitFor();
  const dialog = page.getByRole('alertdialog');
  if (await dialog.isVisible()) await dialog.getByRole('button', { name: '확인', exact: true }).click();
  await shot('11-eyecheck-open');
  await page.getByPlaceholder('A-15, D-24(2)').fill('A-3(2)');
  await page.getByRole('checkbox', { name: '3행 선택', exact: true }).check();
  await shot('12-eyecheck-edit');
  await page.getByRole('tab', { name: '담당자 보고' }).click();
  await page.getByText('신규 2 · 소등 1 · 보고 선택 3', { exact: true }).waitFor();
  await page.getByLabel('보고자 이름', { exact: true }).fill('홍예시');
  for (let i = 0; i < 2; i++) {
    await page.getByLabel('SA3A-3 호스트명', { exact: true }).nth(i).fill(`NEW-HOST-0${i + 1}`);
    await page.getByLabel('SA3A-3 서버 담당자', { exact: true }).nth(i).fill('테스트 책임');
  }
  await page.getByRole('button', { name: '문구 복사', exact: true }).first().click();
  results.eyecheck = await clipboard();
  assert.match(results.eyecheck, /NEW-HOST-01/);
  assert.match(results.eyecheck, /\[소등\]/);
  await shot('13-eyecheck-report');
  await shot('13-eyecheck-fields', page.getByRole('heading', { name: '보고 대상 확인', exact: true }).locator('..'));
  await shot('13-eyecheck-output', page.getByRole('heading', { name: '담당자별 보고 미리보기', exact: true }).locator('..'));
  const downloadWait = page.waitForEvent('download');
  await page.getByRole('button', { name: '새 파일로 내려받기', exact: true }).click();
  const download = await downloadWait;
  await download.saveAs(`${root}samples/eyecheck-result.xlsx`);
  const saved = openEyecheckWorkbook(new Uint8Array(await readFile(await download.path())), 'result.xlsx');
  assert.equal(saved.move.rows.length, 3);
  assert.equal(saved.move.rows.find(row => row.vals.C === 'NEW-HOST-01').vals.L, '테스트 책임');
  await page.getByText('신규 2 · 소등 1 · 보고 선택 3', { exact: true }).waitFor();
  await page.getByRole('button', { name: '붙여넣기로 보고', exact: true }).click();
  await page.getByLabel('아이체크 엑셀 원본 데이터').fill(icheck);
  await page.getByText('보고 대상 2건', { exact: true }).waitFor();
  await shot('14-eyecheck-paste');
  assert.deepEqual(errors, []);
  await writeFile(`${root}results.json`, JSON.stringify({ capturedAt: new Date().toISOString(), results, checks: ['메뉴 순서', 'Message 내부 탭·줄바꿈 복구', '확인 이력 제거', '재전달 복수선택 유지', '백업 Status 0·1 제외', '담당자 미해결 추출 차단', '담당자 확정 XLSX', '아이체크 신규 2·소등 1', '아이체크 저장 후 비교 유지', '13열 붙여넣기 2건', '브라우저 오류 없음'] }, null, 2));
} finally { await browser.close(); }
